version: '3.3'

services:

  klustair-apache:
    container_name: klustair-apache
    build:
      context: ..
      dockerfile: docker/apache/Dockerfile
    image: klustair-apache:latest
    restart: on-failure
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - BROADCAST_DRIVER=${BROADCAST_DRIVER}
      - CACHE_DRIVER=${CACHE_DRIVER}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - SESSION_LIFETIME=${SESSION_LIFETIME}
      - ANCHORE_ENABLE=${ANCHORE_ENABLE:-false}
      - ANCHORE_API_URL=${ANCHORE_API_URL:-http://host.docker.internal:8228}
      - ANCHORE_CLI_USER=${ANCHORE_CLI_USER:-admin}
      - ANCHORE_CLI_PASS=${ANCHORE_CLI_PASS:-foobar}
    ports:
      - 8080:80
      - 8443:443

  klustair-php-fpm:
    image: klustair-php-fpm:latest
    container_name: klustair-php-fpm
    build:
      context: ..
      dockerfile: docker/php-fpm/Dockerfile
    restart: on-failure
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - BROADCAST_DRIVER=${BROADCAST_DRIVER}
      - CACHE_DRIVER=${CACHE_DRIVER}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - SESSION_LIFETIME=${SESSION_LIFETIME}
      - ANCHORE_ENABLE=${ANCHORE_ENABLE:-false}
      - ANCHORE_API_URL=${ANCHORE_API_URL:-http://host.docker.internal:8228}
      - ANCHORE_CLI_USER=${ANCHORE_CLI_USER:-admin}
      - ANCHORE_CLI_PASS=${ANCHORE_CLI_PASS:-foobar}
    ports:
      - "9000:9000"
    volumes:
      - ./php-fpm/config/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini

  klustair-nginx:
    image: klustair-nginx:latest
    container_name: klustair-nginx
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    restart: on-failure
    #command: ["tail", "-f", "/dev/null"]
    #command: ["nginx", "-g", "daemon off;"]
    environment:
      - PHP_FPM_HOST=klustair-php-fpm
    ports:
      - 8080:80
      - 8443:443
    working_dir: /var/www
    expose:
      - 8080
      - 8443
    volumes:
      - ./nginx/config/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/config/etc/ssl:/etc/ssl
    links:
      - klustair-php-fpm
    depends_on:
      - klustair-php-fpm

  klustair-db:
    image: "postgres:12-alpine"
    container_name: klustair-db
    volumes:
      - klustair-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    expose:
      - 5432
    logging:
      driver: "json-file"
      options:
        max-size: 100m

volumes:
  klustair-db-volume:
    # Set this to 'true' to use an external volume. In which case, it must be created manually with "docker volume create anchore-db-volume"
    external: false